services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      # Map the internal media folder to a persistent volume
      - media_volume:/app/media
    restart: always

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      # - "443:443" (Leave commented until SSL is ready)
    volumes:
      # Nginx needs to READ the same folder Gunicorn WRITES to
      - media_volume:/app/media
    depends_on:
      - web
    restart: always

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always

volumes:
  postgres_data_prod:
  media_volume: # Persistent storage for uploads
