upstream django_app {
    server web:8000;
}

server {
    listen 80;
    server_name debastiani.dev www.debastiani.dev localhost;

    # Security: Hide Nginx version
    server_tokens off;

    # 1. Serve Media Files (User Uploads)
    # Nginx serves these directly from disk.
    location /media/ {
        alias /app/media/;
    }

    # 2. Proxy everything else (Home, API, Admin, Static Files) to Gunicorn
    location / {
        proxy_pass http://django_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
        
        # Increase max upload size to 10MB (Project Covers)
        client_max_body_size 10M; 
    }
}