# Generated by Django 5.2.8 on 2026-02-02 18:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Category Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Category",
                "verbose_name_plural": "Project Categories",
            },
        ),
        migrations.CreateModel(
            name="ProjectTechnology",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Technology Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Technology",
                "verbose_name_plural": "Project Technologies",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Project Title"),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=255, verbose_name="Customer Name"),
                ),
                (
                    "short_description",
                    models.TextField(verbose_name="Short Description"),
                ),
                ("long_description", models.TextField(verbose_name="Long Description")),
                (
                    "cover_image",
                    models.ImageField(
                        upload_to="projects/covers/", verbose_name="Cover Image"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=True, verbose_name="Is Featured"),
                ),
                ("started_at", models.DateField(verbose_name="Start Date")),
                (
                    "ended_at",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "live_url",
                    models.URLField(blank=True, null=True, verbose_name="Live URL"),
                ),
                (
                    "repo_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Repository URL"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="portfolio.projectcategory",
                        verbose_name="Project Category",
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(
                        to="portfolio.projecttechnology",
                        verbose_name="Technologies Used",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
    ]
